# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_to_sem_mem.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import MySQLdb as mdb
from contextlib import closing
create_fact = False

class Ui_AddToSemMemWindow(object):
    def setupUi(self, AddToSemMemWindow):
        AddToSemMemWindow.setObjectName("AddToSemMemWindow")
        AddToSemMemWindow.resize(513, 634)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddToSemMemWindow.sizePolicy().hasHeightForWidth())
        AddToSemMemWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(AddToSemMemWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 591, 51))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 1161, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(140, 510, 241, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.DomComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DomComboBox.setGeometry(QtCore.QRect(180, 210, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DomComboBox.setFont(font)
        self.DomComboBox.setObjectName("DomComboBox")
        self.CatComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.CatComboBox.setGeometry(QtCore.QRect(180, 260, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CatComboBox.setFont(font)
        self.CatComboBox.setObjectName("CatComboBox")
        self.TypesComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.TypesComboBox.setGeometry(QtCore.QRect(180, 310, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TypesComboBox.setFont(font)
        self.TypesComboBox.setObjectName("TypesComboBox")
        self.AttrComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.AttrComboBox.setGeometry(QtCore.QRect(180, 360, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttrComboBox.setFont(font)
        self.AttrComboBox.setObjectName("AttrComboBox")
        self.FactsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.FactsComboBox.setGeometry(QtCore.QRect(180, 260, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FactsComboBox.setFont(font)
        self.FactsComboBox.setObjectName("FactsComboBox")
        self.createBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.createBtn.setGeometry(QtCore.QRect(30, 110, 331, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.createBtn.setFont(font)
        self.createBtn.setObjectName("createBtn")
        self.buttonGroup = QtWidgets.QButtonGroup(AddToSemMemWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.createBtn)
        self.convertBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.convertBtn.setGeometry(QtCore.QRect(30, 140, 331, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.convertBtn.setFont(font)
        self.convertBtn.setObjectName("convertBtn")
        self.buttonGroup.addButton(self.convertBtn)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 420, 311, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 310, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 420, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 360, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(390, 110, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startBtn.setFont(font)
        self.startBtn.setObjectName("startBtn")
        AddToSemMemWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddToSemMemWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 22))
        self.menubar.setObjectName("menubar")
        self.menuInteractive_System_Modelling = QtWidgets.QMenu(self.menubar)
        self.menuInteractive_System_Modelling.setObjectName("menuInteractive_System_Modelling")
        AddToSemMemWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddToSemMemWindow)
        self.statusbar.setObjectName("statusbar")
        AddToSemMemWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuInteractive_System_Modelling.menuAction())

        self.retranslateUi(AddToSemMemWindow)
        QtCore.QMetaObject.connectSlotsByName(AddToSemMemWindow)

        self.CatComboBox.hide()
        self.TypesComboBox.hide()
        self.AttrComboBox.hide()
        self.FactsComboBox.hide()
        self.label_5.hide()
        self.label_6.hide()
        self.label_7.hide()
        self.label_9.hide()

        self.version_id = QtWidgets.QLabel(self.centralwidget)
        self.version_id.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.version_id.setObjectName("version_id")

        self.startBtn.clicked.connect(self.startNow)
        self.saveBtn.clicked.connect(self.saveFact)
        self.saveBtn.clicked.connect(AddToSemMemWindow.close)

    def startNow(self):
        version_id = int(self.version_id.text())
        db = mdb.connect('127.0.0.1', 'root', '', 'interSys')
        with closing(db.cursor()) as cur:
            cur.execute("SELECT * FROM domains WHERE version_id = '%i'" % (version_id))
            domains = cur.fetchall()
            for x in domains:
                self.DomComboBox.addItem(x[2])
        self.createBtn.clicked.connect(self.createFact)
        self.convertBtn.clicked.connect(self.convertFact)

    def createFact(self):
        self.CatComboBox.show()
        self.TypesComboBox.show()
        self.AttrComboBox.show()
        self.FactsComboBox.hide()
        self.label_5.show()
        self.label_6.show()
        self.label_7.show()
        self.label_9.hide()
        self.CatComboBox.clear()
        self.TypesComboBox.clear()
        self.AttrComboBox.clear()
        self.FactsComboBox.clear()
        global create_fact
        create_fact = True
        version_id = int(self.version_id.text())
        db = mdb.connect('127.0.0.1', 'root', '', 'interSys')
        with closing(db.cursor()) as cur:
            cur.execute("SELECT * FROM categories WHERE version_id = '%i'" % (version_id))
            categories = cur.fetchall()
            for x in categories:
                self.CatComboBox.addItem(x[2])
            cur.execute("SELECT * FROM types WHERE version_id = '%i'" % (version_id))
            types = cur.fetchall()
            for x in types:
                self.TypesComboBox.addItem(x[2])
            cur.execute("SELECT * FROM attributes WHERE version_id = '%i'" % (version_id))
            attributes = cur.fetchall()
            for x in attributes:
                self.AttrComboBox.addItem(x[2])

    def convertFact(self):
        self.CatComboBox.hide()
        self.TypesComboBox.hide()
        self.AttrComboBox.hide()
        self.FactsComboBox.show()
        self.label_5.hide()
        self.label_6.hide()
        self.label_7.hide()
        self.label_9.show()
        self.CatComboBox.clear()
        self.TypesComboBox.clear()
        self.AttrComboBox.clear()
        self.FactsComboBox.clear()
        version_id = int(self.version_id.text())
        db = mdb.connect('127.0.0.1', 'root', '', 'interSys')
        with closing(db.cursor()) as cur:
            cur.execute("SELECT * FROM facts WHERE version_id = '%i'" % (version_id))
            facts = cur.fetchall()
            for x in facts:
                self.FactsComboBox.addItem(x[2])

    def saveFact(self):
        db = mdb.connect('127.0.0.1', 'root', '', 'interSys')
        version_id = int(self.version_id.text())
        with closing(db.cursor()) as cur:
            cur_dom = str(self.DomComboBox.currentText())
            cur_retr_time = int(str(self.lineEdit.text()))
            global create_fact
            if(create_fact):
                create_fact = False
                cur_fact = str(self.CatComboBox.currentText()) + " " + str(self.TypesComboBox.currentText()) + " " + str(self.AttrComboBox.currentText())
                cur.execute("INSERT INTO sem_mem(version_id, domain, fact, retr_time, categories, types, attributes) VALUES('%i', '%s', '%s', '%i', '%s', '%s', '%s')" 
                        % (version_id, cur_dom, cur_fact, cur_retr_time, ''.join(self.CatComboBox.currentText()), ''.join(self.TypesComboBox.currentText()), ''.join(self.AttrComboBox.currentText())))
            else:
                cur_fact = str(self.FactsComboBox.currentText())
                cur.execute("SELECT * FROM facts WHERE version_id = '%i' AND value = '%s'" % (version_id, cur_fact))
                facts = cur.fetchall()
                for fact in facts:
                    fact_cat = fact[3]
                    fact_type = fact[4]
                    fact_attr = fact[5]
                cur.execute("INSERT INTO sem_mem(version_id, domain, fact, retr_time, categories, types, attributes)"
                        "VALUES('%i', '%s', '%s', '%i', '%s', '%s', '%s')" % (version_id, cur_dom, cur_fact, cur_retr_time, fact_cat, fact_type, fact_attr))
            db.commit()
            QtWidgets.QMessageBox.about(self.centralwidget,'Connection', 'Data Inserted Successfully')



    def retranslateUi(self, AddToSemMemWindow):
        _translate = QtCore.QCoreApplication.translate
        AddToSemMemWindow.setWindowTitle(_translate("AddToSemMemWindow", "MainWindow"))
        self.label.setText(_translate("AddToSemMemWindow", "<html><head/><body><p><span style=\" font-size:28pt;\">Add Fact Representation</span></p></body></html>"))
        self.saveBtn.setText(_translate("AddToSemMemWindow", "Save"))
        self.DomComboBox.setItemText(0, _translate("AddToSemMemWindow", "Animals"))
        self.DomComboBox.setItemText(1, _translate("AddToSemMemWindow", "Dogs"))
        self.CatComboBox.setItemText(0, _translate("AddToSemMemWindow", "Animal"))
        self.CatComboBox.setItemText(1, _translate("AddToSemMemWindow", "Dog"))
        self.TypesComboBox.setItemText(0, _translate("AddToSemMemWindow", "can"))
        self.TypesComboBox.setItemText(1, _translate("AddToSemMemWindow", "has"))
        self.AttrComboBox.setItemText(0, _translate("AddToSemMemWindow", "breathe"))
        self.AttrComboBox.setItemText(1, _translate("AddToSemMemWindow", "move"))
        self.FactsComboBox.setItemText(0, _translate("AddToSemMemWindow", "Animal can breath"))
        self.FactsComboBox.setItemText(1, _translate("AddToSemMemWindow", "Animal can move"))
        self.createBtn.setText(_translate("AddToSemMemWindow", "Create a new fact"))
        self.convertBtn.setText(_translate("AddToSemMemWindow", "Use an existing fact"))
        self.label_4.setText(_translate("AddToSemMemWindow", "Domain"))
        self.label_5.setText(_translate("AddToSemMemWindow", "Category"))
        self.label_6.setText(_translate("AddToSemMemWindow", "Type"))
        self.label_7.setText(_translate("AddToSemMemWindow", "Attribute"))
        self.label_8.setText(_translate("AddToSemMemWindow", "Retrieval time"))
        self.label_9.setText(_translate("AddToSemMemWindow", "Fact"))
        self.startBtn.setText(_translate("EditDatabaseItemWindow", "Start"))
        self.menuInteractive_System_Modelling.setTitle(_translate("AddToSemMemWindow", "1"))

