# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_fact_repr_in_sem_mem.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from functions_with_db import get_domains, get_categories, get_types, get_attributes, get_fact_or_quest_by_value, \
    edit_fact_in_component, edit_quest_in_component, edit_item_in_env, edit_item_in_stm


class Ui_EditItemInComponent(object):
    def setupUi(self, EditItemInComponent):
        EditItemInComponent.setObjectName("EditItemInComponent")
        EditItemInComponent.resize(535, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditItemInComponent.sizePolicy().hasHeightForWidth())
        EditItemInComponent.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(EditItemInComponent)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 591, 51))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 1161, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 96, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.editBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editBtn.setGeometry(QtCore.QRect(390, 130, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.TypesComboBox = QtWidgets.QComboBox(self.centralwidget)
        # self.TypesComboBox.setGeometry(QtCore.QRect(170, 310, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TypesComboBox.setFont(font)
        self.TypesComboBox.setObjectName("TypesComboBox")
        self.for_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.for_lineEdit.setGeometry(QtCore.QRect(200, 470, 311, 41))
        self.for_lineEdit.setObjectName("for_lineEdit")
        self.in_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.in_lineEdit.setGeometry(QtCore.QRect(200, 420, 311, 41))
        self.in_lineEdit.setObjectName("in_lineEdit")
        self.repeat_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.repeat_lineEdit.setGeometry(QtCore.QRect(200, 520, 311, 41))
        self.repeat_lineEdit.setObjectName("repeat_lineEdit")
        self.in_time_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.in_time_lineEdit.setGeometry(QtCore.QRect(200, 570, 311, 41))
        self.in_time_lineEdit.setObjectName("in_time_lineEdit")
        self.CatComboBox = QtWidgets.QComboBox(self.centralwidget)
        # self.CatComboBox.setGeometry(QtCore.QRect(170, 260, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CatComboBox.setFont(font)
        self.CatComboBox.setObjectName("CatComboBox")
        self.DomComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DomComboBox.setGeometry(QtCore.QRect(200, 210, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DomComboBox.setFont(font)
        self.DomComboBox.setObjectName("DomComboBox")
        self.AttrComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.AttrComboBox.setGeometry(QtCore.QRect(200, 360, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AttrComboBox.setFont(font)
        self.AttrComboBox.setObjectName("AttrComboBox")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 470, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 420, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_8")
        self.label_repeat = QtWidgets.QLabel(self.centralwidget)
        self.label_repeat.setGeometry(QtCore.QRect(20, 520, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_repeat.setFont(font)
        self.label_repeat.setObjectName("label_repeat")
        self.label_in_time = QtWidgets.QLabel(self.centralwidget)
        self.label_in_time.setGeometry(QtCore.QRect(20, 570, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_in_time.setFont(font)
        self.label_in_time.setObjectName("label_in_time")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(140, 620, 241, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        # self.label_5.setGeometry(QtCore.QRect(20, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        # self.label_6.setGeometry(QtCore.QRect(20, 310, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 360, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        EditItemInComponent.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditItemInComponent)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 22))
        self.menubar.setObjectName("menubar")
        self.menuInteractive_System_Modelling = QtWidgets.QMenu(self.menubar)
        self.menuInteractive_System_Modelling.setObjectName("menuInteractive_System_Modelling")
        EditItemInComponent.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditItemInComponent)
        self.statusbar.setObjectName("statusbar")
        self.decay_time_label = QtWidgets.QLabel(self.centralwidget)
        self.decay_time_label.setGeometry(QtCore.QRect(20, 420, 201, 31))
        self.decay_time_label.setFont(font)
        self.decay_time_label.setObjectName("decay_time_label")
        self.decay_time_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.decay_time_lineEdit.setGeometry(QtCore.QRect(200, 420, 311, 41))
        self.decay_time_lineEdit.setObjectName("decay_time_lineEdit")
        self.persistence_time_label = QtWidgets.QLabel(self.centralwidget)
        self.persistence_time_label.setGeometry(QtCore.QRect(20, 420, 201, 31))
        self.persistence_time_label.setFont(font)
        self.persistence_time_label.setObjectName("persistence_time_label")
        self.persistence_time_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.persistence_time_lineEdit.setGeometry(QtCore.QRect(200, 420, 311, 41))
        self.persistence_time_lineEdit.setObjectName("persistence_time_lineEdit")
        EditItemInComponent.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuInteractive_System_Modelling.menuAction())
        self.component = ''

        self.retranslateUi(EditItemInComponent)
        QtCore.QMetaObject.connectSlotsByName(EditItemInComponent)

        self.version_id = QtWidgets.QLabel(self.centralwidget)
        self.version_id.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.version_id.setObjectName("version_id")

        self.decay_time_lineEdit.hide()
        self.decay_time_label.hide()
        self.persistence_time_lineEdit.hide()
        self.persistence_time_label.hide()
        self.for_lineEdit.hide()
        self.in_lineEdit.hide()
        self.repeat_lineEdit.hide()
        self.in_time_lineEdit.hide()

        self.label_8.hide()
        self.label_9.hide()
        # self.label_4.hide()
        self.label_repeat.hide()
        self.label_in_time.hide()
        self.decay_time_label.hide()
        self.persistence_time_label.hide()


        self.editBtn.clicked.connect(self.startNow)
        self.saveBtn.clicked.connect(self.saveItem)
        self.saveBtn.clicked.connect(EditItemInComponent.close)

    def saveItem(self):
        version_id = int(self.version_id.text())
        cur_dom = str(self.DomComboBox.currentText())

        if str(self.item) == "facts":
            cur_value = str(self.CatComboBox.currentText()) + " " + str(self.TypesComboBox.currentText()) + " " + str(
                self.AttrComboBox.currentText())
            if self.component == "experiment":
                repeat = int(str(self.repeat_lineEdit.text()))
                repeat_in_time = int(str(self.in_time_lineEdit.text()))
                cur_for_time = int(self.for_lineEdit.text())
                cur_in_time = int(self.in_lineEdit.text())
                params = [cur_dom, cur_value, cur_in_time, cur_for_time, repeat, repeat_in_time,
                          ''.join(self.CatComboBox.currentText()), ''.join(self.TypesComboBox.currentText()),
                          ''.join(self.AttrComboBox.currentText()), version_id, ''.join(self.origin_dom),
                          ''.join(self.origin_value)]
                edit_fact_in_component(params)
        else:
            cur_value = str(self.TypesComboBox.currentText()) + " " + str(self.CatComboBox.currentText()) + " " + str(
                self.AttrComboBox.currentText()) + "?"
            if self.component == "experiment":
                cur_for_time = int(self.for_lineEdit.text())
                cur_in_time = int(self.in_lineEdit.text())
                params = [cur_dom, cur_value, cur_in_time, cur_for_time, ''.join(self.CatComboBox.currentText()),
                          ''.join(self.TypesComboBox.currentText()),
                          ''.join(self.AttrComboBox.currentText()), version_id, ''.join(self.origin_dom),
                          ''.join(self.origin_value)]
                edit_quest_in_component(params)
        if self.component == "environment":
            persistence_time = int(str(self.persistence_time_lineEdit.text()))
            params = [cur_dom, cur_value, persistence_time, ''.join(self.CatComboBox.currentText()), ''.join(self.TypesComboBox.currentText()),
                                                 ''.join(self.AttrComboBox.currentText()), version_id, ''.join(self.origin_dom), ''.join(self.origin_value)]
            edit_item_in_env(params)

        elif self.component == "short_term_mem":
            decay_time = int(str(self.decay_time_lineEdit.text()))
            params = [cur_dom, cur_value, decay_time, ''.join(self.CatComboBox.currentText()), ''.join(self.TypesComboBox.currentText()),
                                                 ''.join(self.AttrComboBox.currentText()), version_id, ''.join(self.origin_dom), ''.join(self.origin_value)]
            edit_item_in_stm(params)
        QtWidgets.QMessageBox.about(self.centralwidget, 'Connection', 'Data Edited Successfully')


    def startNow(self):
        self.DomComboBox.clear()
        self.CatComboBox.clear()
        self.TypesComboBox.clear()
        self.AttrComboBox.clear()
        cur_dom = self.origin_dom
        version_id = int(self.version_id.text())
        domains = get_domains(version_id)
        for x in domains:
            self.DomComboBox.addItem(x[2])
        categories = get_categories(version_id)
        for x in categories:
            self.CatComboBox.addItem(x[2])
        types = get_types(version_id)
        for x in types:
            self.TypesComboBox.addItem(x[2])
        attributes = get_attributes(version_id)
        for x in attributes:
            self.AttrComboBox.addItem(x[2])

        items = get_fact_or_quest_by_value(str(self.item), version_id, ''.join(self.origin_value))
        for x in items:
            if str(self.item) == "facts":
                self.CatComboBox.setCurrentText(x[3])
                self.TypesComboBox.setCurrentText(x[4])
                self.AttrComboBox.setCurrentText(x[5])
            else:
                self.CatComboBox.setCurrentText(x[4])
                self.TypesComboBox.setCurrentText(x[3])
                self.AttrComboBox.setCurrentText(x[5])
        self.DomComboBox.setCurrentText(cur_dom)
        if self.component == "experiment":
            if str(self.item) == "facts":
                self.for_lineEdit.show()
                self.in_lineEdit.show()
                self.repeat_lineEdit.show()
                self.in_time_lineEdit.show()
                self.label_repeat.show()
                self.label_in_time.show()
                self.label_8.show()
                self.label_9.show()
            else:
                self.for_lineEdit.show()
                self.in_lineEdit.show()
                self.label_8.show()
                self.label_9.show()
        elif self.component == "environment":
            self.persistence_time_lineEdit.show()
            self.persistence_time_label.show()

        elif self.component == "short_term_mem":
            self.decay_time_lineEdit.show()
            self.decay_time_label.show()




    def retranslateUi(self, EditItemInComponent):
        _translate = QtCore.QCoreApplication.translate
        EditItemInComponent.setWindowTitle(_translate("EditItemInComponent", "MainWindow"))
        self.label.setText(_translate("EditItemInComponent",
                                      "<html><head/><body><p><span style=\" font-size:28pt;\">Edit</span></p></body></html>"))
        self.label_2.setText(_translate("EditItemInComponent", "Current fact representation"))
        self.label_3.setText(_translate("EditItemInComponent", "Animals - Animal can breath - 1 sec"))
        self.editBtn.setText(_translate("EditItemInComponent", "Edit"))
        self.label_8.setText(_translate("EditItemInComponent", "Available for"))
        self.label_9.setText(_translate("EditItemInComponent", "Starting in"))
        self.saveBtn.setText(_translate("EditItemInComponent", "Save"))
        self.label_4.setText(_translate("EditItemInComponent", "Domain"))
        self.label_5.setText(_translate("EditItemInComponent", "Category"))
        self.label_6.setText(_translate("EditItemInComponent", "Type"))
        self.label_7.setText(_translate("EditItemInComponent", "Attribute"))
        self.label_repeat.setText(_translate("EditItemInComponent", "Repeat"))
        self.label_in_time.setText(_translate("EditItemInComponent", "In time"))
        self.menuInteractive_System_Modelling.setTitle(_translate("EditItemInComponent", "1"))
