# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QWidget, QMessageBox)

from results import Ui_ResultsWindow
from functions_with_db import get_sem_mem, get_env, get_exp
from translation_to_Maude import read_Maude_file, write_stm_capacity_to_Maude, write_cognitive_load_to_Maude, write_decay_time_to_Maude, \
    write_rewrite_steps_to_Maude, write_sem_mem_to_Maude, write_exp_to_Maude, write_env_to_Maude, write_stm_to_Maude, reset_Maude_file, write_to_Maude_file

import MySQLdb as mdb

import subprocess

db = mdb.connect('127.0.0.1', 'root', '', 'interSys')

class Ui_RunProjectWindow(object):
    def setupUi(self, RunProjectWindow):
        RunProjectWindow.setObjectName("RunProjectWindow")
        RunProjectWindow.setFixedSize(480, 800)
        self.centralwidget = QtWidgets.QWidget(RunProjectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 591, 51))
        self.label.setObjectName("label")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.project_name = QtWidgets.QLabel(self.centralwidget)
        self.project_name.setGeometry(QtCore.QRect(40, 80, 351, 51))
        self.project_name.setObjectName("project_name")
        self.project_name.setFont(font)
        self.version_name = QtWidgets.QLabel(self.centralwidget)
        self.version_name.setGeometry(QtCore.QRect(40, 120, 351, 51))
        self.version_name.setObjectName("version_name")
        self.version_name.setFont(font)
        self.version_id = QtWidgets.QLabel(self.centralwidget)
        self.version_id.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.version_id.setObjectName("version_id")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 80, 1161, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 351, 51))
        self.label_2.setObjectName("label_2")
        self.label_2.setFont(font)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 270, 351, 51))
        self.label_4.setObjectName("label_4")
        self.label_4.setFont(font)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 370, 351, 51))
        self.label_5.setObjectName("label_5")
        self.label_5.setFont(font)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 470, 351, 51))
        self.label_6.setObjectName("label_6")
        self.label_6.setFont(font)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 570, 351, 51))
        self.label_7.setObjectName("label_7")
        self.label_7.setFont(font)
        self.stm_capacity = QtWidgets.QLineEdit(self.centralwidget)
        self.stm_capacity.setGeometry(QtCore.QRect(40, 220, 400, 41))
        self.stm_capacity.setObjectName("stm_capacity")
        self.stm_capacity.setFont(font)
        self.cogn_load = QtWidgets.QLineEdit(self.centralwidget)
        self.cogn_load.setGeometry(QtCore.QRect(40, 320, 400, 41))
        self.cogn_load.setObjectName("cogn_load")
        self.cogn_load.setFont(font)
        self.decay_time = QtWidgets.QLineEdit(self.centralwidget)
        self.decay_time.setGeometry(QtCore.QRect(40, 420, 400, 41))
        self.decay_time.setObjectName("decay_time")
        self.decay_time.setFont(font)
        self.in_time = QtWidgets.QLineEdit(self.centralwidget)
        self.in_time.setGeometry(QtCore.QRect(40, 520, 400, 41))
        self.in_time.setObjectName("in_time")
        self.in_time.setFont(font)
        self.rewrite_steps = QtWidgets.QLineEdit(self.centralwidget)
        self.rewrite_steps.setGeometry(QtCore.QRect(40, 620, 400, 41))
        self.rewrite_steps.setObjectName("rewrite_steps")
        self.rewrite_steps.setFont(font)
        self.runBtn = QtWidgets.QPushButton(self.centralwidget)
        self.runBtn.setGeometry(QtCore.QRect(195, 700, 90, 25))
        # self.runBtn.clicked.connect(self.create_project)
        self.runBtn.clicked.connect(RunProjectWindow.close)
        self.runBtn.setFont(font)
        self.runBtn.setObjectName("runBtn")
        RunProjectWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RunProjectWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 22))
        self.menubar.setObjectName("menubar")
        self.menuInteractive_System_Modelling = QtWidgets.QMenu(self.menubar)
        self.menuInteractive_System_Modelling.setObjectName("menuInteractive_System_Modelling")
        RunProjectWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RunProjectWindow)
        self.statusbar.setObjectName("statusbar")
        RunProjectWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuInteractive_System_Modelling.menuAction())

        self.retranslateUi(RunProjectWindow)
        QtCore.QMetaObject.connectSlotsByName(RunProjectWindow)

        self.runBtn.clicked.connect(self.run)

    def get_res_perc(self):
        perc = {}
        env_str = "perc"
        f = open("Maude-2/results.txt", "r")
        i = 0
        for line in f:
            i += 1
            if env_str in line:
                cur_line = str(line)
                mid_line = cur_line.split("<")
                new_line = mid_line[0].split("perc")
                n = len(new_line)
                for x in range(1, n):
                    start = new_line[x].find("(")+len("(")
                    end = new_line[x].find(" for")
                    mid = new_line[x][start:end]
                    start_t = new_line[x].find("for ")+len("for ")
                    end_t = new_line[x].find(")")
                    time = new_line[x][start_t:end_t]
                    perc[mid] = time
        f.close()
        return perc

    def get_res_stm(self):
        stm = {}
        stm_str = "decay"
        f = open("Maude-2/results.txt", "r")
        i = 0
        for line in f:
            i += 1
            if stm_str in line:
                new_line = str(line)
                if new_line.find("goal") != -1:
                    continue
                start = new_line.find("(chunk ")+len("(chunk ")
                end = new_line.find(" decay")
                mid = new_line[start:end]
                start_t = new_line.find("decay ")+len("decay ")
                end_t = new_line.find(" of")
                time = new_line[start_t:end_t]
                if (stm!="INF"):
                    stm[mid] = time
        f.close()
        return stm

    def get_res_time(self):
        time_str = "in time"
        f = open("Maude-2/results.txt", "r")
        i = 0
        for line in f:
            i += 1
            if time_str in line:
                new_line = str(line)
                start = new_line.find("} ")+len("} ")
                end = new_line.find("\nBye")
                mid = new_line[start:end]
        f.close()
        return mid

    def get_res_ans(self):
        ans = {}
        ans_str = "ans"
        f = open("Maude-2/results.txt", "r")
        i = 0
        for line in f:
            i += 1
            if ans_str in line:
                cur_line = str(line)
                start = cur_line.find("(")+len("(")
                end = cur_line.rfind("\"")
                item = cur_line[start:end+1]
                start_t = cur_line.rfind("\" ") + len("\" ")
                end_t = cur_line.find("for")
                time = cur_line[start_t:end_t]
                ans[item] = time
        f.close()
        return ans

    def show_results_window(self):
        self.ResultsWindow = QtWidgets.QMainWindow()
        self.ui = Ui_ResultsWindow()
        self.ui.setupUi(self.ResultsWindow)
        self.ui.label_2.setText(self.label.text())
        self.ui.label_3.setText(self.label_2.text())
        self.ui.version_id.setText(self.version_id.text())

        perc = self.get_res_perc()
        j = 0
        for item, time in perc.items():
            self.ui.envTableWidget.setRowCount(j + 1)
            self.ui.envTableWidget.setItem(j, 0, QtWidgets.QTableWidgetItem(item))
            self.ui.envTableWidget.setItem(j, 1, QtWidgets.QTableWidgetItem(time))
            j += 1

        stm = self.get_res_stm()
        j = 0
        for item, time in stm.items():
            self.ui.stmTableWidget.setRowCount(j + 1)
            self.ui.stmTableWidget.setItem(j, 0, QtWidgets.QTableWidgetItem(item))
            self.ui.stmTableWidget.setItem(j, 1, QtWidgets.QTableWidgetItem(time))
            j += 1

        in_time = self.get_res_time()
        self.ui.label_6.setText(in_time)

    def run(self):

        version_id = int(self.version_id.text())
        sem_mem_dict = get_sem_mem(version_id)
        env_dict = get_env(version_id)
        exp_dict = get_exp(version_id)

        list_of_lines = read_Maude_file()
        write_stm_capacity_to_Maude(list_of_lines, self.stm_capacity.text())
        write_cognitive_load_to_Maude(list_of_lines, self.cogn_load.text())
        # write_decay_time_to_Maude(list_of_lines, self.decay_time.text())
        write_rewrite_steps_to_Maude(list_of_lines, self.rewrite_steps.text(), self.in_time.text())

        list_of_lines = read_Maude_file()

        list_of_lines = write_sem_mem_to_Maude(list_of_lines, sem_mem_dict)
        list_of_lines, i = write_exp_to_Maude(list_of_lines, exp_dict, False)
        list_of_lines = write_env_to_Maude(list_of_lines, env_dict, i)
        list_of_lines = write_stm_to_Maude(list_of_lines, exp_dict, env_dict, False)

        write_to_Maude_file(list_of_lines)
        subprocess.call("./start_maude.sh")

        self.show_results_window()
        reset_Maude_file()
        self.ResultsWindow.show()

    def retranslateUi(self, RunProjectWindow):
        _translate = QtCore.QCoreApplication.translate
        RunProjectWindow.setWindowTitle(_translate("RunProjectWindow", "MainWindow"))
        self.label.setText(_translate("RunProjectWindow", "<html><head/><body><p><span style=\" font-size:28pt;\">Run Project</span></p></body></html>"))
        self.label_2.setText(_translate("RunProjectWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">STM capacity</span></p></body></html>"))
        self.label_4.setText(_translate("RunProjectWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Cognitive Load</span></p></body></html>"))
        self.label_5.setText(_translate("RunProjectWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Decay time</span></p></body></html>"))
        self.label_6.setText(_translate("RunProjectWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">In time</span></p></body></html>"))
        self.label_7.setText(_translate("RunProjectWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Number of rewrite steps</span></p></body></html>"))
        self.stm_capacity.setText(_translate("RunProjectWindow", "7"))
        self.cogn_load.setText(_translate("RunProjectWindow", "0"))
        self.decay_time.setText(_translate("RunProjectWindow", "3"))
        self.in_time.setText(_translate("RunProjectWindow", "1000"))
        self.rewrite_steps.setText(_translate("RunProjectWindow", "10000"))
        self.runBtn.setText(_translate("RunProjectWindow", "Run"))
        self.menuInteractive_System_Modelling.setTitle(_translate("RunProjectWindow", "1"))

