# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_version.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from create_version import Ui_CreateVersionInfoWindow

import MySQLdb as mdb

class Ui_SaveVersionWindow(object):
    def setupUi(self, SaveVersionWindow):
        SaveVersionWindow.setObjectName("SaveVersionWindow")
        SaveVersionWindow.setFixedSize(513, 506)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SaveVersionWindow.sizePolicy().hasHeightForWidth())
        SaveVersionWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(SaveVersionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 591, 51))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 1161, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(70, 100, 381, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(140, 400, 241, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(70, 250, 381, 61))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.currentBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.currentBtn.setGeometry(QtCore.QRect(130, 190, 112, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.currentBtn.setFont(font)
        self.currentBtn.setObjectName("currentBtn")
        self.curNewBtnGroup = QtWidgets.QButtonGroup(SaveVersionWindow)
        self.curNewBtnGroup.setObjectName("curNewBtnGroup")
        self.curNewBtnGroup.addButton(self.currentBtn)
        self.newBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.newBtn.setGeometry(QtCore.QRect(290, 190, 112, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.newBtn.setFont(font)
        self.newBtn.setObjectName("newBtn")
        self.curNewBtnGroup.addButton(self.newBtn)
        self.majorBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.majorBtn.setGeometry(QtCore.QRect(130, 340, 112, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.majorBtn.setFont(font)
        self.majorBtn.setObjectName("majorBtn")
        self.majorMinorBtnGroup = QtWidgets.QButtonGroup(SaveVersionWindow)
        self.majorMinorBtnGroup.setObjectName("majorMinorBtnGroup")
        self.majorMinorBtnGroup.addButton(self.majorBtn)
        self.minorBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.minorBtn.setGeometry(QtCore.QRect(290, 340, 112, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.minorBtn.setFont(font)
        self.minorBtn.setObjectName("minorBtn")
        self.majorMinorBtnGroup.addButton(self.minorBtn)
        self.majorBtn.setEnabled(False)
        self.minorBtn.setEnabled(False)
        SaveVersionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SaveVersionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 22))
        self.menubar.setObjectName("menubar")
        self.menuInteractive_System_Modelling = QtWidgets.QMenu(self.menubar)
        self.menuInteractive_System_Modelling.setObjectName("menuInteractive_System_Modelling")
        SaveVersionWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SaveVersionWindow)
        self.statusbar.setObjectName("statusbar")
        SaveVersionWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuInteractive_System_Modelling.menuAction())

        self.retranslateUi(SaveVersionWindow)
        QtCore.QMetaObject.connectSlotsByName(SaveVersionWindow)

        self.version_name = QtWidgets.QLabel(self.centralwidget)
        self.version_name.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.version_name.setObjectName("version_name")
        self.project_name = QtWidgets.QLabel(self.centralwidget)
        self.project_name.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.project_name.setObjectName("project_name")
        self.version_number = QtWidgets.QLabel(self.centralwidget)
        self.version_number.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.version_number.setObjectName("version_number")
        self.vers_short_descr = QtWidgets.QLabel(self.centralwidget)
        self.vers_short_descr.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.vers_short_descr.setObjectName("vers_short_descr")
        self.vers_long_descr = QtWidgets.QLabel(self.centralwidget)
        self.vers_long_descr.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.vers_long_descr.setObjectName("vers_long_descr")

        self.newBtn.clicked.connect(self.enableBtn)
        self.currentBtn.clicked.connect(self.disableBtn)

        self.saveBtn.clicked.connect(self.save_cur)
        self.saveBtn.clicked.connect(SaveVersionWindow.close)

    def enableBtn(self):
        self.majorBtn.setEnabled(True)
        self.minorBtn.setEnabled(True) 
        self.minorBtn.setChecked(True)  

    def disableBtn(self):
        self.majorBtn.setEnabled(False)
        self.minorBtn.setEnabled(False)        

    def save_cur(self):
        db = mdb.connect('127.0.0.1', 'root', '', 'interSys')
        with db:
            cur = db.cursor()
            if self.currentBtn.isChecked() == True:
                #change the version's components, nothing to change in name, number, or descr
                saveAs = self.currentBtn.text()

            elif self.newBtn.isChecked() == True:
                saveAs = self.newBtn.text()

                if self.majorBtn.isChecked() == True:
                    changes = self.majorBtn.text()
                    ver_numb = float(int(float(self.version_number.text())) + 1)

                elif self.minorBtn.isChecked() == True:
                    changes = self.minorBtn.text()
                    ver_numb = float(self.version_number.text()) + 0.1

                self.CreateVersionInfoWindow = QtWidgets.QMainWindow()
                self.ui = Ui_CreateVersionInfoWindow()
                self.ui.setupUi(self.CreateVersionInfoWindow)
                self.ui.label_3.setText(self.project_name.text())
                self.ui.label_7.setText("Version " + self.version_number.text())
                self.ui.project_name.setText(self.project_name.text())
                self.ui.version_number.setText(str(ver_numb))
                self.CreateVersionInfoWindow.show()

 
            db.commit()
       

    def retranslateUi(self, SaveVersionWindow):
        _translate = QtCore.QCoreApplication.translate
        SaveVersionWindow.setWindowTitle(_translate("SaveVersionWindow", "MainWindow"))
        self.label.setText(_translate("SaveVersionWindow", "<html><head/><body><p><span style=\" font-size:28pt;\">Save Version</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("SaveVersionWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Do you want to save the changes as the current version or as a new version?</span></p></body></html>"))
        self.saveBtn.setText(_translate("SaveVersionWindow", "Save"))
        self.textBrowser_2.setHtml(_translate("SaveVersionWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">The changes are major or minor?</span></p></body></html>"))
        self.currentBtn.setText(_translate("SaveVersionWindow", "Current"))
        self.newBtn.setText(_translate("SaveVersionWindow", "New"))
        self.majorBtn.setText(_translate("SaveVersionWindow", "Major"))
        self.minorBtn.setText(_translate("SaveVersionWindow", "Minor"))
        self.menuInteractive_System_Modelling.setTitle(_translate("SaveVersionWindow", "1"))

