# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'version_desc.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VersionDescWindow(object):
    def setupUi(self, VersionDescWindow):
        VersionDescWindow.setObjectName("VersionDescWindow")
        VersionDescWindow.setFixedSize(553, 416)
        self.centralwidget = QtWidgets.QWidget(VersionDescWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 591, 51))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 1161, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 130, 411, 192))
        self.textBrowser.setObjectName("textBrowser")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        VersionDescWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VersionDescWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 22))
        self.menubar.setObjectName("menubar")
        self.menuInteractive_System_Modelling = QtWidgets.QMenu(self.menubar)
        self.menuInteractive_System_Modelling.setObjectName("menuInteractive_System_Modelling")
        VersionDescWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VersionDescWindow)
        self.statusbar.setObjectName("statusbar")
        VersionDescWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuInteractive_System_Modelling.menuAction())

        self.retranslateUi(VersionDescWindow)
        QtCore.QMetaObject.connectSlotsByName(VersionDescWindow)

    def retranslateUi(self, VersionDescWindow):
        _translate = QtCore.QCoreApplication.translate
        VersionDescWindow.setWindowTitle(_translate("VersionDescWindow", "MainWindow"))
        self.label.setText(_translate("VersionDescWindow", "<html><head/><body><p><span style=\" font-size:28pt;\">Version Description</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("VersionDescWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">This version This version This version This version This version This version This version This version This version This version </span></p></body></html>"))
        self.menuInteractive_System_Modelling.setTitle(_translate("VersionDescWindow", "1"))
